#!/bin/bash
# :vim sw=2:ts=2:et

dancepill() {
  for F in "$@"; do
    if [ -f "$F" ] ; then
      FT1=$(file -bi "$F" | grep -Eo '[[:alnum:]_-]+/[[:alnum:]_-]+')
      DIR=$(mktemp -d -p . -t "$F-XXXXXXXX")
      pushd "$DIR"
      case $FT1 in
        "application/x-bzip2") tar xvjf "../$F" || bunzip2 "../$F" ;;
        "application/x-gzip") tar xvzf "../$F" || gunzip "../$F" ;;
        "application/x-xz") tar xvJf "../$F" ;;
        "application/x-rar") unrar x "../$F" || rar x "../$F" ;;
        "application/x-arj") arj x "../$F" || 7za x "../$F" ;;
        "application/x-lha") lha x "../$F" || 7za x "../$F" ;;
        "application/x-cpio") cpio -i "../$F" ;;
        "application/x-tar") tar xvf "../$F" || gunzip "../$F" ;;
        "application/x-zip") unzip "../$F" ;;
        "application/x-rpm") rpm2cpio "../$F" | cpio -idmv ;;
        "application/zip") unzip "../$F" ;;
        "application/x-7z-compressed") 7za x "../$F" ;;
        "application/x-7za-compressed") 7za x "../$F" ;;
        "application/x-iso9660-image") 7z x "../$F" ;;
        "application/octet-stream") unlzma "../$F" || 7za x "../$F" || uncompress "../$F" ;;
        *) echo "'../$F' ($FT1) cannot be extracted via 'dancepill' shell function" ;;
      esac
      popd
      # expecting only one file/directory to be extracted (prevent mess)
      if [ "$(ls "$DIR" | wc -l)" == "1" ]; then
        mv -v "$DIR"/* . && rmdir "$DIR"
      fi
      # remove empty dir
      rmdir "$DIR" 2>/dev/null
    else
      echo "'$F' is not a valid file"
    fi
  done
}

alias eeee=dancepill
# only set this when it is not defined yet
alias e >/dev/null 2>&1 || alias e=dancepill
